server:
  port: 8082
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: authentication-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter=ADMIN

        - id: paste-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter
#  cloud:
#    gateway:
#      routes:
#        - id: authentication-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/auth/**
#
#        - id: payment-service
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/v1/payment/**
#          filters:
#            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

jwt:
  secret: jhfiuwefiifeiofijo5367566B59703373sdfgfddf367639792F423F4528482B4D6251655468576D5A71347437
